### ISSUE TITLE
Clusterrole cannot approve certificate request from kms-issuer

### ISSUE THREAD

**Issue by leotomas837** [Skyscanner/kms-issuer#187]
Wrong issue. Closed.

**Comment by leotomas837** [comment]
Update: I am indeed stuck and it may be an issue.
I am trying to issue a certificate from my KMSIssuer (status `True`, KMS key created etc), but I am getting the following error message:

```bash
checks.go:95] cert-manager/controller/certificaterequests-issuer-selfsigned/handleSecretReference "msg"="failed to get issuer" "error"="invalid value \"KMSIssuer\" for issuerRef.kind. Must be empty, \"Issuer\" or \"ClusterIssuer\"" "resource_kind"="Secret" "resource_name"="istio-ca-hbd9v" "resource_namespace"="istio-system" "resource_version"="v1"
```

I have obviously added the following in `values.yaml`, as `cert-manager` is the sa for my cert-manager controller:

```yaml
certManagerApprovalRBAC:
  enable: true
  serviceAccountName: cert-manager
  namespace: cert-manager
```

Am I missing something ?

**Comment by leotomas837** [comment]
Note: I am using cert-manager 1.10.0 and here is the `issuerRef` section of my certificate (in accordance with the doc):

```yaml
selector:
    issuerRef:
      name: root
      kind: KMSIssuer
      group: cert-manager.skyscanner.net
```
